##########################################################################################################################################
# Static Provisioning Example
# - https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/examples/kubernetes/static_provisioning/static_provisioning.yaml
# - https://github.com/awslabs/mountpoint-s3-csi-driver/blob/main/examples/kubernetes/static_provisioning/pod_level_identity.yaml
##########################################################################################################################################
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-app-data-pv
spec:
  capacity:
    storage: 12Gi # Ignored, required
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: s3-mount-test # Namespace is required even though it's in "default" namespace.
    name: s3-app-data-pvc # Name of your PVC
  mountOptions:
    - allow-delete
    - region ap-northeast-2
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: s3-csi-driver-volume # Must be unique
    volumeAttributes:
      bucketName: podidentity-app-data-bmp6dt88
      # authenticationSource: pod
      authenticationSource: driver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-app-data-pvc
  namespace: s3-mount-test
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: 12Gi # Ignored, required
  volumeName: s3-app-data-pv # Name of your PV
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-csi-test-sa
  namespace: s3-mount-test
  labels:
    app.kubernetes.io/name: aws-mountpoint-s3-csi-driver
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::252462902626:role/podidentity-mountpoint-s3-csi"
---
apiVersion: v1
kind: Pod
metadata:
  name: s3-app
  namespace: s3-mount-test
spec:
  serviceAccountName: s3-csi-test-sa
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "infinity"]
      volumeMounts:
        - mountPath: "/data"
          name: persistent-storage
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: s3-app-data-pvc
---
