apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv2
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://ap-southeast-1/vol-0ed4c66e6222a87b5
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
