apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv3
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://ap-southeast-1/vol-06609726ea588c9b4
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
