apiVersion: v1
kind: PersistentVolume
metadata:
  name: gp-pv-1
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://ap-northeast-2/vol-0f284e6403dfa874e
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
