apiVersion: v1
kind: PersistentVolume
metadata:
  name: gp-pv-22
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://ap-northeast-2/vol-0eae30fbe36afd150
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
