apiVersion: v1
kind: PersistentVolume
metadata:
  name: gp-pv
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://ap-southeast-1/vol-0e0a437219feffbfa
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
