apiVersion: v1
kind: PersistentVolume
metadata:
  name: gp-pv3
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://ap-southeast-1/vol-06a829973dddcd3a1
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
