apiVersion: v1
kind: PersistentVolume
metadata:
  name: gp-pv4
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://ap-southeast-1/vol-0691e80d934a43acb
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
