apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: jenkins-test
  region: ap-southeast-1
nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 10
