apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::252462902626:role/terraform-assume-role
      username: terraform
      groups:
        - system:masters 