apiVersion: karpenter.k8s.aws/v1alpha1
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ["t"]
    - key: karpenter.k8s.aws/instance-size
      operator: In
      values: ["medium"]
    - key: karpenter.k8s.aws/instance-generation
      operator: In
      values: ["3"]
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 10
      memory: 20Gi
  providerRef:
    name: default
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
  startupTaints:
    - key: node.kubernetes.io/not-ready
      effect: NoSchedule 