apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: gp3-encrypt
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp3
#   fsType: ext4
#   encrypted: "true"
#   # kmsKeyId: arn:aws:kms:ap-northeast-2:252462902626:key/3f2a1e4b-5c6d-7e8f-9012-3456abcdef78
#   tagSpecification_1: "Environment=dev"
#   tagSpecification_2: "Application=dongdorrong"
# volumeBindingMode: WaitForFirstConsumer
# allowVolumeExpansion: true