apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64", "arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          # 2025-08-23 : 사용할 수 있는 values 종류 ["t", "m", "c", "r"]
          values: ["t"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          # 2025-08-23 : 사용할 수 있는 values 종류 ["small", "medium", "large"]
          values: ["large", "xlarge"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["1"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: "8"
    memory: 32Gi
  disruption:
    # WhenEmpty : 노드가 완전히 비어 있을 때 해당 노드를 제거한다.
    # WhenEmptyOrUnderutilized : 노드가 비어 있거나 활용도가 낮을 때 노드를 제거/교체한다.
    # Never : consolidation을 비활성화한다. (노드 제거/교체 없음)
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s