name : project01-ci

on:
  push:
    branch:
      # - master
      - project01

jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Set env
      #   run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push (A)
        uses: docker/build-push-action@v2
        id: docker_build_a
        with:
          context: .
          file: ./project01/resources/container/service_a/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/project01/service_a:latest
      - name: Build and push (B)
        uses: docker/build-push-action@v2
        id: docker_build_b
        with:
          context: .
          file: ./project01/resources/container/service_b/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/project01/service_b:latest
      - name: Build and push (C)
        uses: docker/build-push-action@v2
        id: docker_build_c
        with:
          context: .
          file: ./project01/resources/container/service_c/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/project01/service_c:latest